(ert-deftest eh/functions-bound ()
  (should (fboundp 'evil-hardcore-jump-down))
  (should (fboundp 'evil-hardcore-jump-up))
  (should (fboundp 'evil-hardcore-local-mode))
  (should (fboundp 'evil-hardcore-global-mode)))

(ert-deftest eh/variables-bound ()
  (should (boundp 'evil-hardcore-map)))

(ert-deftest eh/keys-bound ()
  (evil-local-mode 1)
  (evil-hardcore-local-mode 1)
  (should (eq (key-binding "k") 'evil-binding-jump-up))
  (should (eq (key-binding "j") 'evil-binding-jump-down))
  (evil-local-mode -1)
  (evil-hardcore-local-mode -1))
